%
% instructions for genN experiment
%

function instructions = ieeg_instructions()

%
instructions = {};

% general instructions for the experiment
instructions{1} = ...
    ['Siamo pronti a cominciare l''esperimento!' ...
    '\nIl tuo compito sara'' di pronunciare ad alta voce delle parole' ...
    '\nappartenenti a diverse categorie di concetti: animali o professioni.' ...
    '\nSvolgerai questo compito in blocchi da un minuto e mezzo' ...
    '\ne prima dell''inizio di ogni blocco ti verrà indicata la categoria.' ...
    '\nIn totale saranno 12 blocchi.' ...
    '\nNei primi due blocchi, per aiutarti a parlare, sentirai un suono che ti darà un ritmo.' ...
    '\nSeguendo il ritmo dovrai dire tutte le parole che ti vengono in mente riguardo alla categoria indicata.'...
    '\nNei blocchi successivi il suono non sarà più presente,' ... 
    '\ndovrai quindi riprodurre il ritmo che hai praticato.' ...
    '\nAvere un ritmo serve solo ad assicurarsi che non parli ne troppo veloce ne troppo lento.' ...
    '\nRicorda pero'' di parlare in modo naturale,' ...
    '\nnon e'' importante mantenere la velocita'' esatta!'...
    '\nSe notiamo che stai parlando troppo veloce o troppo lento ti avviseremo.' ...
    '\nParla ad alta voce scandendo bene le parole e cerca'...
    '\ndi evitare altri suoni (ad esempio ''mmm'').' ...
    '\nPer iniziare la prova dovrai fissare un puntino rosso al centro dello schermo.' ...
    '\nUna volta iniziata, puoi muovere gli occhi liberamente sullo schermo,' ...
    '\nma cerca di non sbatterli troppo.' ...
    '\nLe prove saranno intervallate da pause indicate sullo schermo' ...
    '\nin cui potrai riposarti.' ...
    '\nInforma lo sperimentatore quando sei pront* a cominciare.' ...
    ];

% instructions at the beginning of each block, with metronome
instructions{2} = ...
    [...
    '\nLa categoria per questo blocco è:' ...        
    '\n%s' ...
    ];
    
% end of first part
instructions{4} = ...
    [...
    'La prima parte dell''esperimento e'' finita!' ...
    '\nPuoi fare ora una pausa.' ...
    '\nInforma lo sperimentatore quando sei pront* a cominciare.' ...
    ];

% end of experiment
instructions{5} = ...
    [...
    'L''esperimento e'' finito!' ...
    '\nGrazie per la partecipazione.' ...
    ];

end