%
% instructions for genN experiment
%

function instructions = ieeg_instructions(ses_id)
% define number range
if contains(ses_id, '12')
    range = [1, 12];
elseif contains(ses_id, '22')
    range = [11, 22];
end

%
instructions = {};

% general instructions for the experiment
instructions{1} = ...
    [ ...
    'Siamo pronti a cominciare l''esperimento!', ...
    sprintf('\nIl tuo compito sara'' di pronunciare i numeri da %d a %d', range(1), range(2)) ...
    '\nnel modo piu'' casuale possibile.' ...
    '\nDopo il suono iniziale, cerca di parlare seguendo'...
    '\nil ritmo del metronomo che hai praticato.' ...
    '\nAvere un ritmo serve solo ad assicurarsi che non parli ne troppo veloce ne troppo lento.' ...
    '\nRicorda pero'' di parlare in modo naturale,' ...
    '\nnon e'' importante mantenere la velocita'' esatta!'...
    '\nSe notiamo che stai parlando troppo veloce o troppo lento ti avviseremo.' ...
    '\nLa prima prova avra'' il metronomo, ma nelle seguenti non ci sara''' ...
    '\ne dovrai cercare di parlare con un ritmo simile.' ...
    '\nParla ad alta voce scandendo bene le parole e cerca'...
    '\ndi evitare altri suoni (ad esempio ''mmm'').' ...
    '\nPer iniziare la prova dovrai fissare un puntino rosso al centro dello schermo.' ...
    '\nUna volta iniziata, puoi muovere gli occhi liberamente,' ...
    '\nma cerca di non sbatterli troppo.' ...
    '\nLe prove saranno intervallate da pause indicate sullo schermo' ...
    '\nin cui potrai riposarti.' ...
    '\nInforma lo sperimentatore quando sei pront* a cominciare.' ...
    ];

% instructions at the end of each block, with metronome
instructions{2} = ...
    [...
    '\nInizierai tra poco il blocco sperimentale' ...
    '\nRicorda le istruzioni:' ...        
    sprintf('\nDopo il beep, pronuncia ad alta voce numeri da %d a %d il piu'' a caso possibile.', range(1), range(2)) ...
    ];

% control instructions
instructions{3} = ...
    [...
    'Faremo ora un calibrazione piu'' approfondita dell''eye tracker.'...
    '\nTi chiederemo di guardare una serie di puntini che appariranno in sequenza sullo schermo.' ...
    '\nIl tuo compito sara'' di fissarli: ' ...
    '\nrimani con lo sguardo fermo sul puntino fino alla comparsa del successivo!'...
    '\nFarai un blocco di questa prova'
    ];
    
% end of first part
instructions{4} = ...
    [...
    'La prima parte dell''esperimento e'' finita!' ...
    '\nPuoi fare ora una pausa.' ...
    '\nInforma lo sperimentatore quando sei pront* a cominciare.' ...
    ];

% end of experiment
instructions{5} = ...
    [...
    'L''esperimento e'' finito!' ...
    '\nGrazie per la partecipazione.' ...
    ];

% resting state
instructions{6} = ...
    [...
    'Faremo ora una pausa di 5 minuti.' ...
    '\nRilassati ma mantieni gli occhi aperti.' ...
    '\nRicordati di non muoverti.' ...
    '\nInformaci quando sei pront* a ricominciare.' ...
    ];

end