%
% instructions for genN experiment
%

function instructions = training_instructions(ses_id)

% define number range
if contains(ses_id , "12")
    range = [1, 12];
elseif contains(ses_id , "22")
    range = [11, 22];
end

%
instructions = {};

% general instructions for the experiment
instructions{1} = ...
    [ ...
    'Siamo pronti a cominciare la pratica!', ...
    sprintf('\nIl tuo compito sara'' di pronunciare i numeri da %d a %d nel modo piu'' casuale possibile.', range(1), range(2)) ...
    '\nDopo il suono iniziale, parla seguendo il ritmo del metronomo che sentirai.' ...
    '\nIl metronomo ha il solo scopo di darti un ritmo, cosi da non parlare troppo veloce ne troppo lento.' ...
    '\nCerca di familiarizzare con questa velocita'' ma allo stesso tempo ricorda di parlare in modo naturale,'...
    '\nnon e'' importante mantenere la velocita'' esatta!' ...
    '\nSe notiamo che stai parlando troppo veloce o troppo lento ti avviseremo.' ...
    '\nNon e'' necessario percio'' sviluppare strategie per memorizzare la velocita'',' ...
    '\nper cui evita di muovere mani/piedi per tenere il tempo.' ...
    '\nParla ad alta voce scandendo bene le parole e cerca di evitare altri suoni (ad esempio ''mmm'').' ...
    '\nLe prove saranno intervallate da pause indicate sullo schermo in cui potrai riposarti.' ...
    '\nInforma lo sperimentatore quando sei pront* a cominciare.' ...
    ];

% instructions before each block, with metronome
instructions{2} = ...
    [...
    'Fine blocco %d/%d' ...
    '\n' ...
    '\nInizierai tra poco il blocco %d/%d' ...
    '\nRicorda le istruzioni:' ...
    sprintf('\nDopo il beep, pronuncia ad alta voce numeri da %d a %d il piu'' a caso possibile.', range(1), range(2)) ...
    '\nRicorda di seguire il ritmo del metronomo, cosi'' da non parlare troppo veloce ne troppo lento.'...
    ];


% end of experiment
instructions{4} = ...
    [...
    'La pratica e'' finita!'
    ];

end